#!/bin/bash
# build-click-handler.sh — generate + register the claude-media:// URL
# handler that makes the statusline segment cmd+clickable.
#
# Two artifacts, both living in the plugin data dir:
#   <data-dir>/ClaudeMediaClick.app   a tiny osacompile applet (LSUIElement,
#                                     no Dock icon) registered for the
#                                     claude-media: URL scheme; its only job
#                                     is to hand the clicked URL to…
#   <data-dir>/click-handler.sh       …which resolves the newest installed
#                                     media.sh (same rule as the statusline
#                                     wrapper) and runs `media.sh open-url`.
#
# The applet embeds only the click-handler.sh PATH (stable across plugin
# updates), so updates just rewrite the .sh — no recompile, no re-register.
# Everything uses macOS-bundled tools: osacompile, plutil, codesign,
# lsregister. No third-party dependencies.
#
# Usage:
#   build-click-handler.sh              ensure app + handler exist (build if
#                                       needed); prints the app path
#   build-click-handler.sh --check-only exit 0 + path if present, else 1
#   build-click-handler.sh --remove     unregister and delete both artifacts
#
# Exit codes: 0 ok, 1 build/registration failed.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Keep in sync with media.sh / build-native.sh.
resolve_data_dir() {
  if [ -n "${CLAUDE_PLUGIN_DATA:-}" ]; then
    echo "$CLAUDE_PLUGIN_DATA"
    return
  fi
  local d
  for d in "$HOME/.claude/plugins/data/media-claude-media-control" \
           "$HOME/.claude/plugins/data/media-inline"; do
    if [ -d "$d" ]; then
      echo "$d"
      return
    fi
  done
  echo "$HOME/.cache/claude-media-control"
}
DATA_DIR="$(resolve_data_dir)"
APP="$DATA_DIR/ClaudeMediaClick.app"
HANDLER_SH="$DATA_DIR/click-handler.sh"
LOG_FILE="$DATA_DIR/build.log"
BUNDLE_ID="com.claude-media-control.click-handler"
# Bumped when the applet source/plist changes — a mismatch forces a rebuild.
APPLET_FORMAT="2"
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"

mode="${1:-}"

if [ "$mode" = "--check-only" ]; then
  if [ -d "$APP" ] && [ -x "$HANDLER_SH" ]; then
    echo "$APP"
    exit 0
  fi
  exit 1
fi

if [ "$mode" = "--remove" ]; then
  if [ -d "$APP" ] && [ -x "$LSREGISTER" ]; then
    "$LSREGISTER" -u "$APP" >/dev/null 2>&1 || true
  fi
  rm -rf "$APP"
  rm -f "$HANDLER_SH"
  exit 0
fi

mkdir -p "$DATA_DIR"

# ---- click-handler.sh (rewritten on every run so plugin updates refresh it) --

# Dev checkouts (claude --plugin-dir) are recorded as a fallback path;
# marketplace installs resolve through the cache glob at click time — the
# newest installed version wins, same as the statusline wrapper.
dev_root=""
case "$PLUGIN_ROOT" in
  */plugins/cache/*) ;;
  *) dev_root="$PLUGIN_ROOT" ;;
esac

MEDIA_CLICK_DEV="$dev_root" /usr/bin/perl -e '
  my $t = do { local $/; <STDIN> };
  my $dev = $ENV{MEDIA_CLICK_DEV} // "";
  $t =~ s/\@DEV\@/$dev/;
  print $t;
' <<'HANDLER_EOF' > "$HANDLER_SH.tmp"
#!/bin/bash
# click-handler.sh — target of the ClaudeMediaClick.app claude-media:// URL
# handler. managed-by: claude-media-control (generated by build-click-handler.sh)
# Resolves the newest installed plugin version at click time, so plugin
# updates never leave a stale path behind.
MEDIA_DEV_ROOT='@DEV@'
MEDIA_DIR="$(ls -d "$HOME"/.claude/plugins/cache/*/media/*/ 2>/dev/null \
  | /usr/bin/awk -F/ '{ print $(NF-1) "\t" $0 }' \
  | /usr/bin/sort -t. -k1,1n -k2,2n -k3,3n \
  | /usr/bin/tail -1 | /usr/bin/cut -f2-)"
MEDIA_SH=""
[ -n "$MEDIA_DIR" ] && MEDIA_SH="${MEDIA_DIR}scripts/media.sh"
if [ ! -x "$MEDIA_SH" ] && [ -n "$MEDIA_DEV_ROOT" ]; then
  MEDIA_SH="$MEDIA_DEV_ROOT/scripts/media.sh"
fi
[ -n "$MEDIA_SH" ] && [ -x "$MEDIA_SH" ] || exit 0
exec "$MEDIA_SH" open-url "${1:-}"
HANDLER_EOF
chmod +x "$HANDLER_SH.tmp"
mv -f "$HANDLER_SH.tmp" "$HANDLER_SH"

# ---- the applet (rebuilt only when missing or its format changed) -----------

if [ -d "$APP" ]; then
  fmt="$(/usr/bin/plutil -extract CFBundleVersion raw "$APP/Contents/Info.plist" 2>/dev/null || true)"
  if [ "$fmt" = "$APPLET_FORMAT" ]; then
    echo "$APP"
    exit 0
  fi
fi

tmp_app="$DATA_DIR/.ClaudeMediaClick.$$.app"
tmp_src="$DATA_DIR/.click-handler.$$.applescript"
trap 'rm -rf "$tmp_app" "$tmp_src"' EXIT

# The applet forwards the URL to click-handler.sh and WAITS for it: the
# handler's osascript sends AppleEvents whose Automation consent tccd
# attributes to the applet. Backgrounding the handler let the applet quit
# first, so the one-time consent dialog raced a send whose responsible
# process was already gone — the send died before anyone could answer, and
# the approval landed on a dead click (measured: grant recorded 18 s after
# the send was cut down). Waiting keeps the applet alive for attribution
# and lets the FIRST click finish its jump the moment consent is granted.
# `try` keeps a nonzero handler exit (nothing playing, refused URL) from
# raising the applet's error dialog. The literal path is escaped for the
# AppleScript string; `quoted form of` shell-quotes it at click time.
MEDIA_CLICK_HANDLER="$HANDLER_SH" /usr/bin/perl -e '
  my $h = $ENV{MEDIA_CLICK_HANDLER};
  $h =~ s/([\\"])/\\$1/g;
  my $t = do { local $/; <STDIN> };
  $t =~ s/\@HANDLER\@/$h/;
  print $t;
' <<'SRC_EOF' > "$tmp_src"
on run
end run

on open location theURL
	try
		do shell script "/bin/bash " & quoted form of "@HANDLER@" & " " & quoted form of theURL & " > /dev/null 2>&1"
	end try
end open location
SRC_EOF

{
  echo "== $(date '+%Y-%m-%dT%H:%M:%S%z') click-handler build =="
} >> "$LOG_FILE" 2>&1 || true

if ! /usr/bin/osacompile -o "$tmp_app" "$tmp_src" >> "$LOG_FILE" 2>&1; then
  echo "media: click-handler build failed (osacompile) — see $LOG_FILE." >&2
  exit 1
fi

plist="$tmp_app/Contents/Info.plist"
if ! /usr/bin/plutil -replace CFBundleIdentifier -string "$BUNDLE_ID" "$plist" >> "$LOG_FILE" 2>&1 \
  || ! /usr/bin/plutil -replace CFBundleVersion -string "$APPLET_FORMAT" "$plist" >> "$LOG_FILE" 2>&1 \
  || ! /usr/bin/plutil -replace LSUIElement -bool true "$plist" >> "$LOG_FILE" 2>&1 \
  || ! /usr/bin/plutil -replace CFBundleURLTypes -json \
       '[{"CFBundleURLName":"Claude Media Control click actions","CFBundleURLSchemes":["claude-media"]}]' \
       "$plist" >> "$LOG_FILE" 2>&1; then
  echo "media: click-handler build failed (Info.plist edit) — see $LOG_FILE." >&2
  exit 1
fi

# Plist edits break the applet stub's bundle seal — re-seal ad hoc so
# LaunchServices/AMFI have nothing to complain about. Best effort: a locally
# built, non-quarantined applet launches either way on current macOS.
/usr/bin/codesign --force --sign - "$tmp_app" >> "$LOG_FILE" 2>&1 || true

rm -rf "$APP"
mv -f "$tmp_app" "$APP"
trap - EXIT
rm -f "$tmp_src"

if [ -x "$LSREGISTER" ]; then
  if ! "$LSREGISTER" -f "$APP" >> "$LOG_FILE" 2>&1; then
    echo "media: click-handler registration failed (lsregister) — see $LOG_FILE." >&2
    exit 1
  fi
else
  # Extremely unlikely; launching once registers the bundle as a fallback.
  /usr/bin/open -g "$APP" >> "$LOG_FILE" 2>&1 || true
fi

echo "== click-handler ok: $APP ==" >> "$LOG_FILE" 2>&1 || true
echo "$APP"
